export const POLICY_VAULT_ABI = [
  "constructor(address _agentNFT, address _defaultTeeKey, address _attestationRegistry)",
  "event AdapterUsed(address indexed adapter, string name)",
  "event Deposited(address indexed user, uint256 amount)",
  "event DepositedToVault(uint256 indexed tokenId, address indexed depositor, uint256 amount)",
  "event EmergencyWithdraw(address indexed owner, uint256 amount)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event PolicyUpdated(uint256 indexed tokenId)",
  "event StrategyExecuted(uint256 indexed tokenId, bytes strategyData, uint256 nonce)",
  "event TeeKeyRotated(address indexed newKey, uint256 timestamp)",
  "event TransferFinalized(uint256 indexed tokenId, address newOwner, uint256 timestamp)",
  "event TransferInitiated(uint256 indexed tokenId, address newOwner, uint256 timestamp)",
  "event Unpaused(address account)",
  "event Withdrawn(address indexed user, uint256 amount)",
  "event WithdrawnVault(uint256 indexed tokenId, address indexed owner, uint256 amount)",
  "function KEY_ROTATION_COOLDOWN() view returns (uint256)",
  "function TRANSFER_COOLDOWN() view returns (uint256)",
  "function agentNFT() view returns (address)",
  "function agentTeeKeys(uint256) view returns (address)",
  "function approvedAdapters(address) view returns (bool)",
  "function attestationRegistry() view returns (address)",
  "function balances(address) view returns (uint256)",
  "function dailySpent(uint256) view returns (uint256)",
  "function defaultTeeKey() view returns (address)",
  "function deposit(uint256 tokenId) payable",
  "function deposit() payable",
  "function emergencyWithdraw()",
  "function executeWithProof(uint256 tokenId, bytes strategyData, uint256 tradeAmount, address targetDEX, bytes signature, uint256 deadline)",
  "function finalizeTransfer(uint256 tokenId)",
  "function getDailySpent(uint256 tokenId) view returns (uint256)",
  "function getNonce(uint256 tokenId) view returns (uint256)",
  "function getPolicy(uint256 tokenId) view returns (tuple(uint256 maxDrawdown, uint256 riskMaxPercent, address[] allowedTokens, address[] allowedDEXs, uint256 dailyLimit))",
  "function getVaultBalance(uint256 tokenId) view returns (uint256)",
  "function initiateTransfer(uint256 tokenId, address newOwner)",
  "function keyRotationUnlocksAt(uint256 tokenId) view returns (uint256)",
  "function lastKeyRotations(uint256) view returns (uint256)",
  "function lastResetDay(uint256) view returns (uint256)",
  "function nonces(uint256) view returns (uint256)",
  "function owner() view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function pendingTransfers(uint256) view returns (address newOwner, uint256 transferInitiatedAt)",
  "function policies(uint256) view returns (uint256 maxDrawdown, uint256 riskMaxPercent, uint256 dailyLimit)",
  "function renounceOwnership()",
  "function setAdapter(address adapter, bool approved)",
  "function setDefaultTeeKey(address _newKey)",
  "function transferOwnership(address newOwner)",
  "function unpause()",
  "function updateAgentTeeKey(uint256 tokenId, address _newKey, bytes32 mrenclave, bytes32 mrsigner)",
  "function updatePolicy(uint256 tokenId, tuple(uint256 maxDrawdown, uint256 riskMaxPercent, address[] allowedTokens, address[] allowedDEXs, uint256 dailyLimit) newPolicy)",
  "function vaultBalances(uint256) view returns (uint256)"
];

export const AGENT_MARKETPLACE_ABI = [
  "constructor(address _agentNFT)",
  "event AgentListed(uint256 indexed tokenId, address indexed seller, uint256 price)",
  "event AgentSold(uint256 indexed tokenId, address indexed seller, address indexed buyer, uint256 price)",
  "event ListingCancelled(uint256 indexed tokenId, address indexed seller)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function PROTOCOL_FEE_BPS() view returns (uint256)",
  "function agentNFT() view returns (address)",
  "function buyAgent(uint256 tokenId) payable",
  "function cancelListing(uint256 tokenId)",
  "function listAgent(uint256 tokenId, uint256 price)",
  "function listings(uint256) view returns (address seller, uint256 price, bool isActive)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address newOwner)"
];

export const SEALED_CLAW_AGENT_ABI = [
  "constructor(uint256 _mintPrice)",
  "event AgentMinted(uint256 indexed tokenId, address indexed owner, string metadataCID)",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)",
  "event MetadataUpdate(uint256 _tokenId)",
  "event MetadataUpdated(uint256 indexed tokenId, string newMetadataCID)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Unpaused(address account)",
  "event UsageAuthorized(uint256 indexed tokenId, address indexed agent, uint256 permissions)",
  "event UsageRevoked(uint256 indexed tokenId, address indexed agent)",
  "function approve(address to, uint256 tokenId)",
  "function authorizeUsage(uint256 tokenId, address agent, uint256 permissions)",
  "function balanceOf(address owner) view returns (uint256)",
  "function burn(uint256 tokenId)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function mintAgent(string metadataCID) payable",
  "function mintPrice() view returns (uint256)",
  "function name() view returns (string)",
  "function owner() view returns (address)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function renounceOwnership()",
  "function revokeUsage(uint256 tokenId, address agent)",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function setMintPrice(uint256 _price)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function totalMinted() view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function transferOwnership(address newOwner)",
  "function unpause()",
  "function updateMetadata(uint256 tokenId, string newCID)",
  "function withdrawFees()"
];

export const CHAINLINK_ORACLE_VERIFIER_ABI = [
  "constructor()",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function addFeed(string pair, address feed)",
  "function getPrice(string pair) view returns (uint256 price, uint256 updatedAt)",
  "function owner() view returns (address)",
  "function priceFeeds(bytes32) view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address newOwner)",
  "function validatePrice(string pair, uint256 agentPrice, uint256 toleranceBps) view returns (bool)"
];
